[DBGPRINT] _tmain(): Use '_tcscpy()' instead of overkill '_tcsncpy()'
Fix GCC 'RelWithDebInfo'
'sdk/include/crt/tchar.h:1410:18: error: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]'